home/urls.py
from django.conf.urls import patterns, include, url

from home.views import home_page

urlpatterns = patterns(
    '',
    url(r'^$', home_page, name='index'),
)

reglog_app/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from . import settings
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', include('home.urls', namespace='home')),
    url(r'^login/', include('login.urls', namespace='login', app_name='login')),
    url(r'^register/', include('register.urls', namespace='register', app_name='register')),

    url(r'^test-reset/', include('test_reset.urls', namespace='test_reset', app_name='test_reset')),

    url(r'^admin/', include(admin.site.urls)),
) \
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # \
    #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, render_to_response
from django.template import RequestContext


def home_page(request):
    context = {}
    #return render(request, 'home/index.html')
    return render_to_response('home/index.html',
                              context,
                              context_instance=RequestContext(request))

home/templates/home/index.html
<!DOCTYPE html>
<html>

<head>

  <meta http-equiv="Content-Type" content="text-html; charset=utf-8" />
  <meta name="description" content="" />
  <meta name="keywords" content="" />
  <meta name="author" content="" />

  <title>Home Page for www.reglog.apu</title>

  <link rel="stylesheet" type="text/css" href="/static/css/style.css" />

  <script type="text/javascript" src="/static/js/jquery-1.6.2.min.js"></script>

  <script type="text/javascript">
    $(document).ready(function() {
      $("#index_login").click(function() {
          window.location.href = "{% url "login:index" %}"
      });
      $("#index_registration").click(function() {
          window.location.href = "{% url "register:index" %}"
      });
    });
  </script>

</head>

<body>

<div id="index_main_div">
  <div id="index_login">
      <a href="{% url "login:index" %}">Login</a>
  </div>
  <div id="index_registration">
      <a href="{% url "register:index" %}">Registration</a>
  </div>
<a href="http://www.djangoproject.com/"><img src="https://www.djangoproject.com/m/img/badges/djangomade124x25.gif" border="0" alt="Made with Django." title="Made with Django." /></a>
</div>

</body>

</html>