home/urls.py
from django.conf.urls import patterns, include, url

from home.views import home_page

urlpatterns = patterns(
    '',
    url(r'^$', home_page, name='index'),
)

login/urls.py
from django.conf.urls import patterns, url
#from login.forms import PasswordResetForm, ChangePasswordForm
#from login import forms

#from django.contrib.auth.forms import SetPasswordForm


urlpatterns = patterns(
    '',
    url(r'^$', 'login.views.process_login', name='index'),

    url(r'dummy-ajax/$',
        'login.views.dummy_ajax',
        name='dummy-ajax'),

    url(r'check-username/$',
        'login.views.ajax_login_username_check',
        name='ajax-usercheck'),  # AJAX
    url(r'^loged-in/$', 'login.views.loged_in', name='logedin'),
    url(r'^show-portrait/$', 'login.views.show_portrait', name='show_portrait'),
    url(r'^loged-out/$', 'login.views.loged_out', name='logedout'),
    url(r'^logout/$', 'login.views.process_logout', name='logout'),
    url(r'^login-error/$', 'login.views.login_error', name='login-error'),

    # For resetting a password (user has lost his password).
    # view: password_reset
    # This view presents the form for typing in the email address to which will
    # be sent a one time usable link.
    url(r'password_reset/$',
        'login.views.password_reset',
        name='password_reset'),

    # The view which show the page after a user has been emailed a link to
    # reset the password. This view is called by default if password_reset()
    # view doesn't have an explicit post_reset_redirect URL set.
    url(r'password_reset/done/$',
        'login.views.password_reset_done',
        name='password_reset_done'),

    # view: password_reset_confirm
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'login.views.password_reset_confirm',
        name='password_reset_confirm'),

    # view: password_reset_complete
    url(r'^reset/done/$',
        'django.contrib.auth.views.password_reset_complete',
        {'template_name': 'login/password_reset_complete.html'},
        name='password_reset_complete'),
)

reglog_app/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from . import settings
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', include('home.urls', namespace='home')),
    url(r'^login/', include('login.urls', namespace='login', app_name='login')),
    url(r'^register/', include('register.urls', namespace='register', app_name='register')),

    url(r'^test-reset/', include('test_reset.urls', namespace='test_reset', app_name='test_reset')),

    url(r'^admin/', include(admin.site.urls)),
) \
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # \
    #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

login/forms.py
from django import forms
from django.contrib.auth.models import User  # Important for hashing passwords!
                                             # And for using built in table, extending by my own data.

#from register.models import User_Data

from django.contrib.sites.models import Site
from django.template import Context, loader
from django.contrib.auth.tokens import default_token_generator
from django.utils.translation import ugettext_lazy as _
#from django.utils.http import int_to_base36
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes


class LoginForm(forms.Form):
    """ Login form """
    username = forms.CharField(label='Username:')

    password = forms.CharField(widget=forms.PasswordInput, label='Password:')

    def __unicode__(self):
        return "%s" % (self.username, )

    def clean_username(self):
        """
        Custom validation:
            if user doesn't exists raise error.
        """
        try:
            User.objects.get(username=self.cleaned_data['username'])

        except User.DoesNotExist:
            raise forms.ValidationError('The user ' +
                                        str(self.cleaned_data['username']) +
                                        ' is not registered yet!')

        return self.cleaned_data['username']


class PasswordResetForm(forms.Form):
    """ Forgot Password Form """
    email = forms.EmailField(label='e-mail:')

    # I need these for substitution of text in template.
    formname = 'Password Reset Form'
    formname2 = 'password_reset_form'

    def clean_email(self):
        try:
            self.users_cache = User.objects.filter(email__iexact=self.cleaned_data['email'])

        except User.DoesNotExist:
            raise forms.ValidationError('No such email address!')

        return self.cleaned_data['email']

    def save(self,
             request,
             from_email=None,
             subject_template_name=None,
             domain_override=None,
             html_email_template_name='login/password_reset_email.html',
             email_template_name='login/password_reset_email.html',
             use_https=False,
             token_generator=default_token_generator):
        """
        Generates a one-use only link for resetting password and sends to the user
        """
        from django.core.mail import send_mail
        for user in self.users_cache:
            if not domain_override:
                current_site = Site.objects.get_current()
                site_name = current_site.name
                domain = current_site.domain
            else:
                site_name = domain = domain_override
            t = loader.get_template(email_template_name)
            c = {
                'email': user.email,
                'domain': domain,
                'site_name': site_name,
                #'uid': int_to_base36(user.id),
                'uid': urlsafe_base64_encode(force_bytes(user.id)),  # this was the BUGGGGHHH!
                'user': user,
                'token': token_generator.make_token(user),
                'protocol': use_https and 'https' or 'http',
            }
            send_mail(_("Password reset on %s") % site_name,
                      t.render(Context(c)), None, [user.email])


class ChangePasswordForm(forms.Form):
    """
    This form is for changeing password.
    It represents two textboxes for entering and confirming new password.
    """
    new_password1 = forms.CharField(label='New Password:',
                                    widget=forms.PasswordInput)

    new_password2 = forms.CharField(label='Confirm New Password:',
                                    widget=forms.PasswordInput)

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(ChangePasswordForm, self).__init__(*args, **kwargs)

    def __unicode__(self):
        return "Instance of ChangePasswordForm"

    def clean(self):
        if 'new_password1' in self.cleaned_data and 'new_password2' in self.cleaned_data:
            new_pass1 = self.cleaned_data['new_password1']
            new_pass2 = self.cleaned_data['new_password2']
            if new_pass1 != new_pass2:
                raise forms.ValidationError('Passwords must match!')

        return self.cleaned_data

    def save(self, commit=True):
        self.user.set_password(self.cleaned_data['new_password1'])
        if commit:
            self.user.save()
        return self.user

login/views.py
from django.shortcuts import render_to_response, redirect
from django.http import HttpResponseRedirect, HttpResponse  # Http404
from django.template import RequestContext
from django.contrib import auth
from django.contrib.auth.models import User
from django.contrib.auth import views

#from django.utils import simplejson
#import json
#from django.core.context_processors import csrf

from django.views.decorators.csrf import csrf_protect
#from django.contrib.auth.decorators import login_required

from django.contrib.auth.tokens import default_token_generator

#from django.core.mail import send_mail

from django.core.urlresolvers import reverse  # , resolve

#from django.contrib.auth.views import (password_reset,  # password_reset_complete,
#                                       password_reset_confirm)

from register.models import User_Data
from login.forms import LoginForm, PasswordResetForm, ChangePasswordForm


def dummy_ajax(request):
    print "I called dummy, ajax after blur from username field on form."
    return HttpResponse("OK")


@csrf_protect
def ajax_login_username_check(request):
    #c = {}
    #c.update(csrf(request))

    if request.method == 'GET' and request.GET['u']:
        searchfor = request.GET['u']

        try:
            u = User.objects.get(username=searchfor)
            print('Successfully accomplished query.')
            print(u.last_name)

        except User.DoesNotExist:
            print('There is NO such user name')
            #c = {'check': 'Error', }
            return HttpResponse('ERR')

    #c = {'check': 'OK', }
    return HttpResponse('OK')
    #return HttpResponse(c)


def process_login(request):
    """
    View function for loging in a site.
    """

    if request.user.is_authenticated():
        return redirect('login:logedin')

    if request.method == 'POST':

        form = LoginForm(request.POST)

        if form.is_valid():
            #return HttpResponse('THE FORM IS VALID!')
            #return HttpResponse(form.cleaned_data['username'])
            # Assigning & clearing input values.
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            #return HttpResponse('username is: %s' % username)
            #return HttpResponse('password is: %s' % password)

            # Checking username with database username value.
            #return HttpResponse('AUTHENTICATING!')
            user = auth.authenticate(username=username, password=password)
            #return HttpResponse('AUTHENTICATED!')
            #return HttpResponse('user is: %s' % user)

            if user is not None and user.is_active:
                #return HttpResponse('TRYING TO LOGIN!')
                auth.login(request, user)
                #return HttpResponse('LOGGED IN!')
                return HttpResponseRedirect(reverse('login:logedin'))

            else:
                # This is fired if javascript is disabled in browser.
                return HttpResponseRedirect(reverse('login:login-error'))

    else:
        form = LoginForm()  # An unbound form.

    context = {
        'form': form,
        'formname': 'Login',
    }

    return render_to_response('login/login-index.html',
                              context,
                              context_instance=RequestContext(request))


def process_logout(request):
    auth.logout(request)

    return HttpResponseRedirect(reverse('login:logedout'))


def forgot_password_context_processor(request):
    return {
        'formname2': 'Forgot Password',

    }


def forgot_password(request):
    context = {}
    return render_to_response(
        'login/forgot_password.html',
        context,
        context_instance=RequestContext(request))


@csrf_protect
def password_reset(request):
    """
    This uses password_reset url name.
    """
    template_response = views.password_reset(request,
                                             template_name='login/password_reset_form.html',
                                             email_template_name='login/password_reset_email.html',
                                             post_reset_redirect='login:password_reset_done',
                                             password_reset_form=PasswordResetForm,
                                             current_app='login')

    return template_response


def password_reset_done(request):
    """
    The page  shown after a user has been emailed a link to reset their password.
    This view is called after email with a link  was sent to the user.
    Returns template response too.
    """
    template_response = views.password_reset_done(request,
                                                  template_name='login/password_reset_done.html',
                                                  current_app='login')

    return template_response


def password_reset_confirm(request, uidb64, token):
    """
    password_reset_confirm function is used from django.
    This function presents a form for entering a new password.
    """
    template_response = views.password_reset_confirm(request, uidb64=uidb64, token=token,
                                                     token_generator=default_token_generator,
                                                     template_name='login/password_reset_confirm.html',
                                                     #template_name='registration/password_reset_confirm.html',
                                                     post_reset_redirect='login:password_reset_complete',
                                                     set_password_form=ChangePasswordForm,
                                                     extra_context={'formname': 'Password Reset Confirmation',
                                                                    'formname2': 'password_reset_confirm'}
                                                     )

    return template_response

#"""
#password_reset_complete.
#Presents a view which informs the user that the password has been successfully changed.
#"""


def password_reset_succesfully_changed(request):
    pass


#@login_required
def loged_in(request):
    if request.user.is_authenticated():
        context = {}

        return render_to_response('login/you_are_loged_in.html',
                                  context,
                                  context_instance=RequestContext(request))
    else:
        return redirect('login:index')


def loged_out(request):
    context = {}

    return render_to_response('login/you_are_loged_out.html',
                              context,
                              context_instance=RequestContext(request))


def login_error(request):
    """
    This is required if javascript is disabled in the browser.
    """
    context = {}

    return render_to_response('login/login-error.html',
                              context,
                              context_instance=RequestContext(request))


#@login_required
def show_portrait(request):
    """
    Provide a link to a picture of the current user.
    """
    if request.user.is_authenticated():
        # query the portrait end part from db.
        user = User_Data.objects.get(user=request.user.id)

        if user.portrait.url:
            portpath = user.portrait.url
            print(portpath)
            context = {'user': user,
                       'portpath': portpath}

            return render_to_response('login/show_portrait.html',
                                      context,
                                      context_instance=RequestContext(request))
        else:
            return HttpResponseRedirect('/no/available/portrait/')


def no_portrait(request):
    context = {}
    return render_to_response('login/no_portrait.html',
                              context,
                              context_instance=RequestContext(request))

login/templates/login/login-error.html
{% load staticfiles %}

<!DOCTYPE html>
<html>

<head>

  <meta http-equiv="Content-Type" content="text-html; charset=utf-8" />
  <meta name="description" content="" />
  <meta name="keywords" content="" />
  <meta name="author" content="" />

  <title>Error While Login</title>

  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

  <script type="text/javascript" src="{% static 'js/jquery-1.6.2.min.js' %}"></script>

<body>

<div id="header_li_lo_rs">
  <h2><span style="color: red;">Error</span></h2>
</div>
  <div id="main_li_lo_rs_div">
    <table id="li_lo_rs_table">
      <tr>
        <td><h4>Wrong password!</h4></td>
      </tr>
      <tr>
          <td>Try again <a href="{% url 'login:index' %}">Login</a></td>
      </tr>
      <tr>
          <td>Or did You <a href="{% url 'login:password_reset' %}">Forgot a password</a>?</td>
      </tr>
      <tr>
          <td><a href="{% url 'home:index' %}"><span style="color:#006600; font-size:1.8em;">home</span></a></td>
      </tr>
    </table>
  </div>
</body>

</html>

login/templates/login/login-index.html
{% extends 'form_base.html' %}

{% block title %}Login Form{% endblock %}

{% block focus %}
<script type="text/javascript">
  function focus_first_element() {
    document.getElementById('{{ form.username.auto_id }}').focus();
  }
</script>
{% endblock %}

{% block header %}
<div id="header_{{ formname|lower }}">
  <h2>{{ formname }} Form</h2>
</div>
{% endblock %}

{% comment %}
{% block er %}
{% if form.errors %}
  <p style="color: red;">
  Please correct the error{{ form.errors|pluralize }} bellow.
  </p>
{% endif %}
{% endblock %}
{% endcomment %}

{% block form %}

{% comment %}
      {% if form.errors %}
        <div class="error_div">
          {# {{ form.non_field_errors }} #}
          {% if form.username.errors %}
          {{ form.username.errors }}
          {% endif %}
          {% if form.password.errors %}
            {{ form.password.errors }}
          {% endif %}
        </div>
      {% endif %}
{% endcomment %}

      <tr>
        <td>{{ form.username.label }}</td>
        <td width="10px">
          {%if form.username.errors %}
            <span class="error">!</span>
          {% else %}
            *
          {% endif %}
        </td>
        <td>{{ form.username }}</td>
        {% if form.username.errors %}
        <td nowrap>{{ form.username.errors }}</td>
        {% endif %}
      </tr>
      <tr>
        <td>{{ form.password.label }}</td>
        <td width="10px">
          {%if form.password.errors %}
            <span class="error">!</span>
          {% else %}
            *
          {% endif %}
        </td>
        <td>{{ form.password }}</td>
      </tr>
      <td>
        <a href="{% url 'register:index' %}">Not Registered?</a>
          <br />
          <a href="{% url 'login:password_reset' %}">Forgot a password?</a>
          <br />
          <a href="{% url 'home:index' %}"><span style="color:#006600; font-size:1.8em;">home</span></a>
        </td>
        <td width="10px"></td>
        <td><input type="submit" id="submit" value="Login" /></td>
      </tr>
{% endblock form %}

login/templates/login/password_reset_complete.html
<!DOCTYPE html>
<html>

<head>

  <meta http-equiv="Content-Type" content="text-html; charset=utf-8" />
  <meta name="description" content="" />
  <meta name="keywords" content="" />
  <meta name="author" content="" />

  <title>Password Changed Successfully</title>

  <link rel="stylesheet" type="text/css" href="/static/css/style.css" />

  <script type="text/javascript" src="/static/js/jquery-1.6.2.min.js"></script>

<body>

<div id="header_li_lo_rs">
  <h2>Password Changed Successfully!</h2>
</div>
  <div id="main_li_lo_rs_div">
    <table id="li_lo_rs_table">
      <tr>
        <td><p>Your password has been changed successfully!</p></td>
      </tr>
      <tr>
        <td><p>Now you can mess around after login.</p></td>
      </tr>
      <tr>
          <td><a href="{% url 'login:index' %}">Login</a></td>
      </tr>
      <tr>
        <td>Or just go 
            <a href="{% url 'home:index' %}"><span style="color:#006600; font-size:1.8em;">home</span></a>
        </td>
      </tr>
    </table>
  </div>

</body>

</html>

login/templates/login/password_reset_confirm.html
{% extends 'form_base.html' %}
{% load i18n %}

{% block title %}{% trans "Change Password Confirmation" %}{% endblock %}

{% block focus %}
<script type="text/javascript">
  function focus_first_element() {
    document.getElementById('{{ form.new_password1.auto_id }}').focus();
  };
</script>
{% endblock %}

{% block header %}
<div id="header_{{ formname2 }}">
  <h2>{{ formname }}</h2>
</div>
{% endblock %}

{% block form %}
{% if validlink %}
        {{ form.formname }}
        {{ from.formname2 }}

      {% if form.errors %}
        <div class="error_div">
          {% if from.new_password1.errors %}
            {{ form.new_password1.errors }}
          {% endif %}
          {% if from.new_password2.errors %}
            {{ form.new_password2.errors }}
          {% endif %}
        </div>
      {% endif %}

      <tr>
        <td>{{ form.new_password1.label }}</td>
        <td width="10px">
          {% if form.new_password1.errors %}
            <span class="error">!</span>
          {% else %}
            *
          {% endif %}
        </td>
        <td>{{ form.new_password1 }}</td>
      </tr>
      <tr>
        <td>{{ form.new_password2.label }}</td>
        <td width="10px">
          {% if form.new_password2.errors %}
            <span class="error">!</span>
          {% else %}
            *
          {% endif %}
        </td>
        <td>{{ form.new_password2 }}</td>
      </tr>
        <td>
            <a href="{% url 'home:index' %}"><span style="color:#006600; font-size:1.8em;">home</span></a>
        </td>
        <td width="10px"></td>
        <td><input type="submit" id="submit" value="Submit" /></td>
      </tr>
{% else %}
<p>validlink is False.</p>
{% endif %}
{% endblock form %}

login/templates/login/password_reset_done.html
{% load staticfiles %}

<!DOCTYPE html>
<html>

<head>

  <meta http-equiv="Content-Type" content="text-html; charset=utf-8" />
  <meta name="description" content="" />
  <meta name="keywords" content="" />
  <meta name="author" content="" />

  <title>Request for New Password is Sent</title>

  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

  <script type="text/javascript" src="{% static 'js/jquery-1.6.2.min.js' %}"></script>

<body>

<div id="header_request_email_sent">
  <h2>Your Request for New Password is Sent!</h2>
</div>
  <div id="main_request_email_sent">
    <table id="request_email_sent_table">
      <tr>
        <td>Your request is sent to your email address.<br />Please follow the provided link in the email.</td>
      </tr>
      <tr>
        <td>You will be redirected from your email link to the page where you can change your password.</td>
      </tr>
      <tr>
        <td><a href="{% url 'home:index' %}"><span style="color:#006600; font-size:1.8em;">Home</span></a></td>
      </tr>
    </table>
  </div>
</body>

</html>

login/templates/login/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'login:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

login/templates/login/password_reset_form.html
{% extends 'form_base.html' %}

{% block title %}{{ form.formname }}{% endblock %}

{% block focus %}
<script type="text/javascript">
  function focus_first_element() {
    document.getElementById('{{ form.email.auto_id }}').focus();
  };
</script>
{% endblock %}

{% block header %}
<div id="header_{{ form.formname2 }}">
  <h2>{{ form.formname }}</h2>
</div>
{% endblock %}

{% block form %}

      {% if form.errors %}
        <div class="error_div">
          {# {{ form.non_field_errors }} #}
          {% if from.email.errors %}
            {{ form.email.errors }}
          {% endif %}
        </div>
      {% endif %}

      <tr>
        <td colspan="3">Type your valid email address in the field bellow, that we can send you an email with a link wich will redirect you to a form where you can reset your password.</td>
      </tr>
      <td></td>
      <tr>
        <td>{{ form.email.label }}</td>
        <td width="10px">
          {% if form.email.errors %}
            <span style="color: red;">!</span>
          {% else %}
            *
          {% endif %}
        </td>
        <td>{{ form.email }}</td>
      </tr>
        <td>
          <a href="{% url 'register:index' %}">Not Registered?</a>
          <br />
          <a href="{% url 'home:index' %}"><span style="color:#006600; font-size:1.8em;">home</span></a>
        </td>
        <td width="10px"></td>

        <input type="hidden" value="{{ csrf_token}}" name="csrfmiddlewaretoken" />

        <td><input type="submit" id="submit" value="Send" /></td>
      </tr>
{% endblock %}

login/templates/login/show_portrait.html
{% load staticfiles %}

<!DOCTYPE html>
<html>

<head>

  <meta http-equiv="Content-Type" content="text-html; charset=utf-8" />
  <meta name="description" content="" />
  <meta name="keywords" content="" />
  <meta name="author" content="" />

  <title>You Are Loged In</title>

  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

  <script type="text/javascript" src="{% static 'js/jquery-1.6.2.min.js' %}"></script>

<body>

<div id="header_li_lo_rs">
  <h2>You are Loged In</h2>
</div>
  <div id="main_li_lo_rs_div">
    <table id="li_lo_rs_table">
      <tr>
        <td>Wow, you are looking pretty nice!</td>
        <td><img src="{{ user.portrait.url }}" alt="{{ user.get_username }}"></td>
      </tr>
      <tr>
        <td><a href="{% url 'login:logedin' %}">Back</a></td>
      </tr>
      <tr>
          <td><a href="{% url 'home:index' %}"><span style="color:#006600; font-size:1.8em;">home</span></a></td>
      </tr>
    </table>
  </div>

</body>

</html>

login/templates/login/working_login_template.html
{% extends 'form_base.html' %}

{% block title %}Login Form{% endblock %}

{% block focus %}
<script type="text/javascript">
  function focus_first_element() {
    document.getElementById('{{ form.username.auto_id }}').focus();
  }
</script>
{% endblock %}

{% block header %}
<div id="header_{{ formname|lower }}">
  <h2>{{ formname }} Form</h2>
</div>
{% endblock %}

{% comment %}
{% block er %}
{% if form.errors %}
  <p style="color: red;">
  Please correct the error{{ form.errors|pluralize }} bellow.
  </p>
{% endif %}
{% endblock %}
{% endcomment %}

{% block form %}

      {% if form.errors %}
        <div class="error_div">
          {# {{ form.non_field_errors }} #}
          {% if form.username.errors %}
            {{ form.username.errors }}
          {% endif %}
          {% if form.password.errors %}
            {{ form.password.errors }}
          {% endif %}
        </div>
      {% endif %}

      <tr>
        <td>{{ form.username.label }}</td>
        <td width="10px">
          {%if form.username.errors %}
            <span class="error">!</span>
          {% else %}
            *
          {% endif %}
        </td>
        <td>{{ form.username }}</td>
      </tr>
      <tr>
        <td>{{ form.password.label }}</td>
        <td width="10px">
          {%if form.password.errors %}
            <span class="error">!</span>
          {% else %}
            *
          {% endif %}
        </td>
        <td>{{ form.password }}</td>
      </tr>
      <td>
        {% comment %}{% url reglog.register.views.process_register as register %}{% endcomment %}
        {% comment %}<a href="{% url 'register' %}">Not Registered?</a>{% endcomment %}
        <a href="{% url "register:index" %}">Not Registered?</a>
          <br />
          <a href="/login/password/reset/">Forgot a password?</a>
          <br />
          <a href="/"><span style="color:#006600; font-size:1.8em;">home</span></a>
        </td>
        <td width="10px"></td>
        <td><input type="submit" id="submit" value="Login" /></td>
      </tr>
{% endblock form %}

login/templates/login/wrong_username_or_password.html
{% load staticfiles %}

<!DOCTYPE html>
<html>

<head>

  <meta http-equiv="Content-Type" content="text-html; charset=utf-8" />
  <meta name="description" content="" />
  <meta name="keywords" content="" />
  <meta name="author" content="" />

  <title>Error While Login</title>

  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

  <script type="text/javascript" src="{% static 'js/jquery-1.6.2.min.js' %}"></script>

<body>

<div id="header_li_lo_rs">
  <h2><span style="color: red;">Error</span></h2>
</div>
  <div id="main_li_lo_rs_div">
    <table id="li_lo_rs_table">
      <tr>
        <td><h4>Wrong password!</h4></td>
      </tr>
      <tr>
          <td>Try again <a href="{% url 'login:index' %}">Login</a></td>
      </tr>
      <tr>
          <td>Or did You <a href="{% url 'login:password_reset' %}">Forgot a password</a>?</td>
      </tr>
    </table>
  </div>
</body>

</html>

login/templates/login/you_are_loged_in.html
{% load staticfiles %}

<!DOCTYPE html>
<html>

<head>

  <meta http-equiv="Content-Type" content="text-html; charset=utf-8" />
  <meta name="description" content="" />
  <meta name="keywords" content="" />
  <meta name="author" content="" />

  <title>You Are Loged In</title>

  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

  <script type="text/javascript" src="{% static 'js/jquery-1.6.2.min.js' %}"></script>

<body>

<div id="header_li_lo_rs">
  <h2>You are Loged In</h2>
</div>
  <div id="main_li_lo_rs_div">
    <table id="li_lo_rs_table">
      <tr>
        <td>Great, You can now mess around!</td>
      </tr>
      <tr>
        <td>If you are interesting about how you look like click on this link.</td>
        <td><a href="{% url "login:show_portrait" %}">Your Portrait</a></td>
      </tr>
      <tr>
          <td><a href="{% url "login:logout" %}">Logout</a></td>
      </tr>
      <tr>
          <td><a href="{% url 'home:index' %}"><span style="color:#006600; font-size:1.8em;">home</span></a></td>
      </tr>
    </table>
  </div>

</body>

</html>

login/templates/login/you_are_loged_out.html
{% load staticfiles %}

<!DOCTYPE html>
<html>

<head>

  <meta http-equiv="Content-Type" content="text-html; charset=utf-8" />
  <meta name="description" content="" />
  <meta name="keywords" content="" />
  <meta name="author" content="" />

  <title>You Are Loged Out</title>

  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

  <script type="text/javascript" src="{% static 'js/jquery-1.6.2.min.js' %}"></script>

<body>

<div id="header_li_lo_rs">
  <h2>You are Loged Out</h2>
</div>

  <div id="main_li_lo_rs_div">

    <table id="li_lo_rs_table">
      <tr>
        <td>
          <p>Thank You for visiting our site.</p>
          <p>Good bye or login again.</p>
        </td>
      </tr>
      <tr>
          <td><a href="{% url "login:index" %}">Login again</a></td>
      </tr>
      <tr>
          <td><a href="{% url 'home:index' %}"><span style="color:#006600; font-size:1.8em;">home</span></a></td>
      </tr>
    </table>

  </div>
</body>

</html>